# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('documents', '0001_initial'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('materials_description', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.BusinessCategory')),
                ('documents', models.ManyToManyField(to='documents.Document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
                ('visual_form_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.VisualFormFactor')),
            ],
        ),
    ]
