# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.DataBatch')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='customers.Operator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='materials_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.MeterialsDescription'),
        ),
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
