# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160729_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
