# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'verbose_name_plural': 'business categories'},
        ),
    ]
