# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('work_email', models.EmailField(max_length=254)),
                ('home_email', models.EmailField(blank=True, max_length=254)),
                ('work_address', models.CharField(max_length=100)),
                ('home_address', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('skype', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('mcc', models.CharField(max_length=3)),
                ('area_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Country')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Operator'),
        ),
    ]
