# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20160731_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
