# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160729_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databatch',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
