# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160729_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databatch',
            options={'verbose_name_plural': 'data batches'},
        ),
    ]
