# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160731_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databatch',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
